services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=firstspringdb
      - POSTGRES_USER=lihindu
      - POSTGRES_PASSWORD=lihindu123
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
